import express from "express";
import { deleteUser, deleteUser2, getUser, getUsers, signOut, testController, updateUser } from "../controllers/user.controller.js";
import { verifyToken } from "../utils/verifyUser.js";
const router = express.Router();
router.get('/test',testController);
router.put('/update/:userId',verifyToken,updateUser);
router.delete('/delete/:userId',verifyToken,deleteUser);
router.post('/signout',signOut);
router.get('/getUsers',verifyToken,getUsers);
router.delete('/deleteUser/:deleteUserId/:userId',verifyToken,deleteUser2);
router.get('/getUser/:userId',getUser);
export default router;